name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Login DockerHub
      uses: actions/docker/login@master
      env: 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jiangfengbing/sql-advisor:latest
    - name: Push the Docker image
      run: docker push jiangfengbing/sql-advisor:latest
